// AUTHORED-BY Claude Fable 5
//
// Renders a run report (lib/runner.mjs output) as the markdown scoreboard.
// The scoreboard is honest by construction: executed pass/fail is reported
// separately from every flavour of "did not execute", audit-class statements
// are evidence-checks (never pass/fail), and a non-JLWS baseline target's
// failures are labelled findings about the spec delta, not bugs.

const CATEGORY_LABELS = {
  pass: 'pass',
  fail: 'FAIL',
  'untested-setup-error': 'untested (state realisation refused)',
  'untested-unrealizable': 'untested (state/agent not realisable black-box)',
  'untested-precondition': 'skipped (optional feature not provided — conformant)',
  'untested-library': 'untested (library-level vector; bind in-process)',
  'untested-filtered': 'untested (excluded by case filter — partial run)',
  'external-suite': 'covered by an external suite (adopted by reference)',
  'no-vector': 'no vector yet (companion test gap)',
  'audit-evidence': 'evidence-check (audit-class A-int/A-exist)',
  premature: 'untestable (premature — P)',
  'not-applicable': 'not applicable (non-server conformance class)',
};

const md = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

const pct = (n, d) => (d === 0 ? '—' : `${Math.round((n / d) * 100)}%`);

export function renderMarkdown(report, { baselineNote = null } = {}) {
  const { meta, summary, statements } = report;
  const lines = [];
  const push = (...xs) => lines.push(...xs);

  push(
    '<!-- AUTHORED-BY Claude Fable 5 -->',
    '<!-- GENERATED by test-suite/bin/run.mjs — do not edit by hand; re-run the suite instead. -->',
    '',
    `# JLWS conformance report — ${md(meta.label)}`,
    '',
    `| | |`,
    `|---|---|`,
    `| Target | \`${meta.target}\` |`,
    `| Generated | ${meta.generatedAt} |`,
    `| Harness | jlws-conformance-suite ${meta.harnessVersion} |`,
    `| Statement companions (spec pin) | core \`${meta.companionPins.core?.slice(0, 12)}\`, rdf-transform \`${meta.companionPins['rdf-transform']?.slice(0, 12)}\` |`,
    `| Vector suite pin | \`${meta.vectorPin}\` (${meta.vectorCount} cases) |`,
    `| Target features/capabilities declared | ${
      [...meta.features, ...meta.capabilities].join(', ') || '(none)'
    } |`,
    `| Agent credential seams configured | ${meta.agentsConfigured} |`,
    '',
  );

  if (baselineNote) push('> ' + baselineNote.split('\n').join('\n> '), '');

  push(
    '## How to read this scoreboard',
    '',
    '- The report is keyed to the **normative-statement companion IDs** (`index.statements.ttl`, `rdf-transform.statements.ttl`).',
    '- Only **server-deniable, enforceable (E)** statements execute, through their wired `http-exchange` vectors.',
    '- **Audit-class (A-int / A-exist)** statements are listed as evidence-checks — an implementation satisfies them by review/attestation, never by a vector.',
    '- **Premature (P)** statements are explicitly untestable today.',
    '- `untested (…)` rows are honest non-execution, each with the reason; they are **not** passes.',
    '- SHOULD/MAY-level failures are reportable, not disqualifying (W3C practice).',
    '',
  );

  push('## Headline — executed statements', '');
  push('| Level | Executed | Pass | Fail | Pass rate |', '|---|---|---|---|---|');
  for (const [level, h] of Object.entries(summary.headline)) {
    if (h.executed === 0) continue;
    push(`| ${level} | ${h.executed} | ${h.pass} | ${h.fail} | ${pct(h.pass, h.executed)} |`);
  }
  const totalExec = Object.values(summary.headline).reduce((a, h) => a + h.executed, 0);
  const totalPass = Object.values(summary.headline).reduce((a, h) => a + h.pass, 0);
  push(`| **all** | **${totalExec}** | **${totalPass}** | **${totalExec - totalPass}** | **${pct(totalPass, totalExec)}** |`, '');

  push('## Statement disposition — all statements', '');
  push('| Disposition | Count |', '|---|---|');
  for (const cat of Object.keys(CATEGORY_LABELS)) {
    const n = summary.statements.byCategory[cat] ?? 0;
    if (n > 0) push(`| ${CATEGORY_LABELS[cat]} | ${n} |`);
  }
  push(`| **total** | **${summary.statements.total}** |`, '');

  const executed = statements.filter((s) => s.category === 'pass' || s.category === 'fail');
  for (const spec of ['core', 'rdf-transform']) {
    const rows = executed.filter((s) => s.spec === spec);
    if (rows.length === 0) continue;
    push(`## Executed statements — ${spec === 'core' ? 'JLWS Core Protocol' : 'RDF Content Transformation Profile'}`, '');
    push('| Statement | Level | Result | Wired vectors (disposition) |', '|---|---|---|---|');
    for (const s of rows) {
      const cases = s.caseResults.map((c) => `\`${c.id}\` (${c.disposition})`).join('<br>');
      const anchor = s.anchor ? s.anchor.slice(s.anchor.indexOf('#')) : '';
      push(`| **${s.id}** ${anchor} | ${s.level} | ${s.category === 'pass' ? 'pass' : '**FAIL**'} | ${cases} |`);
    }
    push('');
  }

  const failed = statements.filter((s) => s.category === 'fail');
  if (failed.length > 0) {
    push('## Findings (failed statements)', '');
    for (const s of failed) {
      push(`### ${s.id} — ${s.level} (${s.spec})`, '', `> ${md(s.statement)}`, '');
      for (const c of s.caseResults) {
        if (c.disposition !== 'fail') continue;
        push(`- \`${c.id}\` — ${md(c.title ?? '')}`);
        for (const f of (c.failures ?? []).slice(0, 6)) push(`  - ${md(f)}`);
        if ((c.failures ?? []).length > 6) push(`  - … ${(c.failures ?? []).length - 6} more`);
      }
      push('');
    }
  }

  const buckets = [
    ['untested-setup-error', 'Untested — the target refused the state-realisation writes'],
    ['untested-unrealizable', 'Untested — declared state/agents not realisable black-box on this target'],
    ['untested-precondition', 'Skipped — optional feature not provided (conformant skip)'],
    ['untested-library', 'Untested — library-level vectors (bind the abstract operation in-process)'],
    ['untested-filtered', 'Untested — excluded by the case filter (partial run)'],
    ['external-suite', 'Covered by an external suite adopted by reference'],
    ['no-vector', 'No vector yet — the companion test-gap backlog'],
    ['audit-evidence', 'Evidence-checks — audit-class statements (A-int / A-exist)'],
    ['premature', 'Premature (P)'],
    ['not-applicable', 'Not applicable — non-server conformance classes'],
  ];
  for (const [cat, title] of buckets) {
    const rows = statements.filter((s) => s.category === cat);
    if (rows.length === 0) continue;
    push(`## ${title} (${rows.length})`, '');
    push('| Statement | Level | Subject(s) | Detail |', '|---|---|---|---|');
    for (const s of rows) {
      const detail =
        cat === 'audit-evidence'
          ? md(s.comment ?? s.categoryDetail)
          : cat === 'no-vector'
            ? `gap: ${s.testGap ?? '?'}`
            : md(s.categoryDetail);
      push(`| ${s.id} | ${s.level} | ${s.subjects.join(', ')} | ${detail.slice(0, 220)} |`);
    }
    push('');
  }

  push('## Case annex — every vector, this run', '');
  push('| Case | Disposition | Note |', '|---|---|---|');
  for (const [id, r] of Object.entries(report.cases)) {
    push(`| \`${id}\` | ${r.disposition} | ${md(r.detail ?? '').slice(0, 200)} |`);
  }
  push(
    '',
    `${summary.unwiredCases} vector(s) are not wired to any statement — they pin keywordless clauses recorded as extraction-note errata candidates in the companions.`,
    '',
  );

  return lines.join('\n');
}
